replicaCount: 3

image:
  repository: gcr.io/nanoblog/nanoblog
  tag: 0.1.2
  pullPolicy: IfNotPresent

redis:
  image:
    pullPolicy: IfNotPresent
  cluster:
    enabled: false
  existingSecret: "nanoblog-redis"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: mclement.dev
      paths:
        - "/"
    - host: www.mclement.dev
      paths:
        - "/"
  tls:
   - secretName: mclement-dev-cf-tls
     hosts:
       - mclement.dev
       - www.mclement.dev

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
