apiVersion: skaffold/v1beta11
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: gcr.io/nanoblog/nanoblog
deploy:
  helm:
    releases:
    - name: nanoblog
      chartPath: ./charts/nanoblog
      skipBuildDependencies: false
      wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      values:
        image: gcr.io/nanoblog/nanoblog
      #recreatePods will pass --recreate-pods to helm upgrade
      recreatePods: true
      #overrides builds an override values.yaml file to run with the helm deploy
      #overrides:
      # some:
      #   key: someValue
      #setValues get appended to the helm deploy with --set.
      #setValues:
#some.key: someValue
