[package]
name = "postctl"
version = "0.1.0"
authors = ["Matt Clement <m@nullroute.host>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
